
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author awdsa
 */
public class CheckOutWindow extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutWindow
     */
    ShoppingCartWindow window1 = new ShoppingCartWindow();
    SearchWindow window2 = new SearchWindow();
    ArrayList<Customer> custList = new ArrayList<Customer>();
    boolean modify = false;
    String title = "";
    String state= "";
    int state_index;
    
    double total;
    int order;
    
    public CheckOutWindow() {
        initComponents();
    }
    
    public CheckOutWindow(ArrayList<Customer> custList,double total, int order, ShoppingCartWindow window) {
        initComponents();
        this.custList = custList;
        this.total=total;
        this.order = order;
        this.window1 = window;
    }
    
    public CheckOutWindow(ArrayList<Customer> custList,double total, int order, SearchWindow window2,Customer cust) {
        initComponents();
        this.custList = custList;
        this.total=total;
        this.order = cust.getOrder();
        this.window2 = window2;
        modify = true;
        title = cust.getTitle();
        state = cust.getState();
        
        
        
        fname_jTextField.setText(cust.getFirstN()); 
        lname_jTextField.setText(cust.getLastN()); 
        addr1_jTextField.setText(cust.getAddr1());
        addr2_jTextField.setText(cust.getAddr2());
        city_jTextField.setText(cust.getCity());
        if(title.equals("Mr"))
            mr_jRadioButton.setSelected(true);
        else if(title.equals("Mrs"))
            mrs_jRadioButton.setSelected(true);
        else if(title.equals("Miss"))
            miss_jRadioButton.setSelected(true);
        
        if(state.equals("California"))
            state_index = 0;
        if(state.equals("New York"))
            state_index = 1;
        if(state.equals("Alabama"))
            state_index = 2;
        if(state.equals("Pennsylvania"))
            state_index = 3;
        if(state.equals("Alaska"))
            state_index = 4;
        if(state.equals("Texas"))
            state_index = 5;
        state_jComboBox.setSelectedIndex(state_index);
        
        post_jTextField.setText(cust.getPost());
        visa_jPasswordField.setText(cust.getVisa());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mr_jRadioButton = new javax.swing.JRadioButton();
        mrs_jRadioButton = new javax.swing.JRadioButton();
        miss_jRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fname_jTextField = new javax.swing.JTextField();
        lname_jTextField = new javax.swing.JTextField();
        addr1_jTextField = new javax.swing.JTextField();
        addr2_jTextField = new javax.swing.JTextField();
        city_jTextField = new javax.swing.JTextField();
        post_jTextField = new javax.swing.JTextField();
        state_jComboBox = new javax.swing.JComboBox<>();
        cancel_jButton = new javax.swing.JButton();
        submit_jButton = new javax.swing.JButton();
        visa_jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Title");

        buttonGroup1.add(mr_jRadioButton);
        mr_jRadioButton.setText("Mr");

        buttonGroup1.add(mrs_jRadioButton);
        mrs_jRadioButton.setText("Mrs");

        buttonGroup1.add(miss_jRadioButton);
        miss_jRadioButton.setText("Miss");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Address 1");

        jLabel5.setText("Address 2");

        jLabel6.setText("City");

        jLabel7.setText("State");

        jLabel8.setText("Post code");

        jLabel9.setText("Visa");

        state_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "California", "New York", "Alabama", "Pennsylvania", "Alaska", "Texas" }));
        state_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state_jComboBoxActionPerformed(evt);
            }
        });

        cancel_jButton.setText("Cancel");
        cancel_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_jButtonActionPerformed(evt);
            }
        });

        submit_jButton.setText("Submit");
        submit_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(mr_jRadioButton)
                                        .addGap(31, 31, 31)
                                        .addComponent(mrs_jRadioButton)
                                        .addGap(51, 51, 51)
                                        .addComponent(miss_jRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(state_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fname_jTextField)
                                            .addComponent(lname_jTextField)
                                            .addComponent(city_jTextField)
                                            .addComponent(post_jTextField)
                                            .addComponent(visa_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(addr2_jTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addr1_jTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cancel_jButton)
                        .addGap(84, 84, 84)
                        .addComponent(submit_jButton)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mr_jRadioButton)
                    .addComponent(mrs_jRadioButton)
                    .addComponent(miss_jRadioButton))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lname_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addr1_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addr2_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(city_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(state_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(post_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(visa_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_jButton)
                    .addComponent(submit_jButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_jButtonActionPerformed

        if(mr_jRadioButton.isSelected())
            title = "Mr";
        else if(mrs_jRadioButton.isSelected())
            title = "Mrs";
        else if(miss_jRadioButton.isSelected())
            title = "Miss";
        
        String firstN = fname_jTextField.getText(); 
        String lastN= lname_jTextField.getText(); 
        String addr1= addr1_jTextField.getText();
        String addr2= addr2_jTextField.getText();
        String city= city_jTextField.getText();
        String state= (String) state_jComboBox.getSelectedItem();
        String postcode= post_jTextField.getText();
        char[] visa= visa_jPasswordField.getPassword();
        
        Customer cust = new Customer(title,firstN,lastN,addr1,addr2,city,state,postcode,visa,total,order);
        
        
        String message;
        int current_index=0;
       
        for(int i=0;i<custList.size();i++)
        {
            if(custList.get(i).getOrder()==order)
            {
                
                current_index = i;
            }
        }
        
        if(modify)
        {
            custList.set(current_index,cust);
            message = "Order(Number ="+order+") has been updated succesfully.";
            JOptionPane.showMessageDialog(null, message, "Order info", 1);
        }
        
        else
        {
            custList.add(cust);
            message = "Order(Number ="+order+") has been created succesfully."; 
            JOptionPane.showMessageDialog(null, message, "Order info", 1);
            order++;
            window1.updateInfo(custList,order);
        }
        
        dispose();
       
        
        
    }//GEN-LAST:event_submit_jButtonActionPerformed

    private void cancel_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_jButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancel_jButtonActionPerformed

    private void state_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_state_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr1_jTextField;
    private javax.swing.JTextField addr2_jTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_jButton;
    private javax.swing.JTextField city_jTextField;
    private javax.swing.JTextField fname_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname_jTextField;
    private javax.swing.JRadioButton miss_jRadioButton;
    private javax.swing.JRadioButton mr_jRadioButton;
    private javax.swing.JRadioButton mrs_jRadioButton;
    private javax.swing.JTextField post_jTextField;
    private javax.swing.JComboBox<String> state_jComboBox;
    private javax.swing.JButton submit_jButton;
    private javax.swing.JPasswordField visa_jPasswordField;
    // End of variables declaration//GEN-END:variables
}
